services:
  db:
    container_name: mysql-80
    image: mysql:8.4
    platform: linux/amd64
    ports:
      - "8036:3306"
    restart: always
    environment:
      MYSQL_DATABASE: app_db
    # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ort
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./dbdata:/var/lib/mysql
  phpmyadmin:
    container_name: pma-80
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    links:
      - db
volumes:
  dbdata:
