services:
  db:
    container_name: mysql-80
    image: mysql:8.4
    platform: linux/amd64
    ports:
      - "8036:3306" #a gauche port ouvert coter machine et a droite coter docker
    restart: always
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./dbdata:/var/lib/mysql #le : permet la separation entre le coter machine et le coter docker
  phpmyadmin:
    container_name: pma-80
    image: phpmyadmin/phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
      MEMORY_LIMIT: 512M
      MAX_EXECUTION_TIME: 0
    restart: always
    links:
      - db
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8081:8080"
#    environment:
#      ADMINER_DEFAULT_SERVER: db
#      ADMINER_DESIGN: "lucas-sandery"
#    links:
#      - db
volumes:
  dbdata:
